version: '3'
volumes:
  todos-vol:
services:
  bot:
    build: ./
    ports:
      - "5500:5500"
    depends_on:
      - db

  db:
    image: postgres:12.7-alpine
    container_name: db
    ports:
      - 5432:5433
    environment:
      POSTGRES_PASSWORD: pwd  # environment variable that sets the superuser password for PostgreSQL
      POSTGRES_USER: usr # variable that will create the specified user
      POSTGRES_DB: todos # the name of your db
    volumes:
      - todos-vol:/var/lib/postgresql/data
    restart: always

